# Generated by Django 2.2.4 on 2019-08-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Tipo'),
            preserve_default=False,
        ),
    ]
